### ISSUE TITLE
Opening output file '/opt/robotframework/reports/output.xml' failed: Permission denied

### ISSUE THREAD

**Issue by renukavipin** [ppodgorsek/docker-robot-framework#279]
Hi,
I am using the image ppodgorsek/robot-framework:latest for executing my robot framework tests in gitlab. It was successfully running till 13-May-2020. Now I am getting the error mentioned in the title "Opening output file '/opt/robotframework/reports/output.xml' failed: Permission denied". My gitlab-ci.yml file looks like 
`
```yaml
image: docker:stable
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
- docker:dind

stages:
  - test

Test:
  stage: test
  script:
    - ./test-linux.sh
  artifacts:
    when: on_failure
    expire_in: 2 weeks
    paths:
    - ./reports
````
and my test-linux.sh file looks like this
`docker run \
	    --shm-size=1g \
	    -e ROBOT_OPTIONS="-v BROWSER:chrome" \
	    -v `pwd`/reports:/opt/robotframework/reports:Z \
	    -v `pwd`/tests:/opt/robotframework/tests:Z \
	    ppodgorsek/robot-framework:latest`
Can you please look into this issue?
