### ISSUE TITLE
Rebot seems not to run in dockerimage

### ISSUE THREAD

**Issue by peterfranssen** [ppodgorsek/docker-robot-framework#379]
**Describe the bug**
I tried to follow the steps in of the earlier reported issues in about rerunning failed tests. The rerunning is working fine, but it seems not to merge the results and produces additional logging

**To Reproduce**
Currently I managed to get below code running, including running failed tests. I assume the issue is somewhere in grabbing the output files from the correct path and merging them. Both the output files are created in the reports directory. 

```
docker run --rm \
  -v ${PWD}/reports:/opt/robotframework/reports:Z \
  -v ${PWD}/rfafricapwa/tests:/opt/robotframework/tests:Z \
  --mount type=bind,source=${PWD}/rfafricapwa/resources,target=/opt/robotframework/resources \
  --user $(id -u):$(id -g) \
  ppodgorsek/robot-framework:latest ||
      
docker run --rm \
  -v ${PWD}/reports:/opt/robotframework/reports:Z \
  -v ${PWD}/rfafricapwa/tests:/opt/robotframework/tests:Z \
  --mount type=bind,source=${PWD}/rfafricapwa/resources,target=/opt/robotframework/resources \
  -e ROBOT_OPTIONS="--rerunfailed /opt/robotframework/reports/output.xml -o output2.xml" \
  --user $(id -u):$(id -g) \
  ppodgorsek/robot-framework:latest ||
  
docker run --rm \
  -v ${PWD}/reports:/opt/robotframework/reports:Z \
  -e REBOT_OPTIONS="-d /opt/robotframework/reports -l logpaadesktop -x junitoutput --merge /opt/robotframework/reports/output*.xml" \
  --user $(id -u):$(id -g) \
  ppodgorsek/robot-framework:latest
```

The part with uploads the reports:

```
# Publish testresults to Github Actions
        - name: Publish Unit Test Results
          uses: mikepenz/action-junit-report@v2
          if: always()
          with:
            report_paths: ${{ github.workspace }}/reports/*.xml
            update_check: true
            check_name:   "SK AF PWA - Daily Regression Test"
        # upload test reports as a zip file
        - name: Upload reports
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            # set path to Robot Framework results reports. Exclude dummy file that is needed because of ppodgorsek image priviledges.
            path: ${{ github.workspace }}/reports
```

![image](https://user-images.githubusercontent.com/94632865/146900279-cd44e1a3-e361-4bc4-af26-4e9ac1c9b4a9.png)

![image](https://user-images.githubusercontent.com/94632865/146900366-f59ca255-21f4-4bd5-8e61-b1f8190dec90.png)
