### ISSUE TITLE
GitLab CI/CD Artifact Report Export

### ISSUE THREAD

**Issue by UnaffiliatedCode** [ppodgorsek/docker-robot-framework#381]
### Affected Source:
GitLab CI/CD
### Problem Statement:
As part of a CI/CD pipeline, I would like to be able to export the reports folder as an artifact of the build. 

### Issue Description
User Does not have permission within the $PWD/root/bin folders of the project. This blocks the duplication of the report result from the intended folder /opt/robotframework/reports to $PWD/$ArtifactStoragePath

### Attempted Solution
``` yaml
robot:
  stage: Robo_Testing
  image: ppodgorsek/robot-framework:latest
  variables:
    ROBOT_REPORTS_DIR: /opt/robotframework/reports/
    ROBOT_TESTS_DIR: /opt/robotframework/temp/robot/tests/
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - /reports/
    expire_in: 1 week
  before_script:
    - cp -Rv $CI_PROJECT_DIR/robot/ /opt/robotframework/
  script:
    - exec /opt/robotframework/bin/run-tests-in-virtual-screen.sh 
  after_script:
    - cp -r /opt/robotframework/reports/ $CI_PROJECT_DIR/reports/
```

**Additional context**
The goal here is to provide a localized export option within the CI/CD pipelines. Alternatively, you "could" store the entire docker image as an artifact, however the image size is +2.5GB.  The reports themselves would be much smaller and easier to digest as a disposable object. 

As an easy solution, I was able to replicate the repository and remove the user assignment (to run the application within the CI/CD as a ROOT user). This however would require several minutes with each deployment in order to construct the image, or an alternative docker image host.

In practice the subfolder target would be /builds/$REPOSITORY_HOST/$REPOSITORY_NAME
or "/builds/username/SomeRepository"

**Comment by ppodgorsek** [comment]
I'm not sure I understand what you are trying to achieve here, as the reports folder in the container can be mounted to any folder of your choosing.

Couldn't you create the `/builds/$REPOSITORY_HOST/$REPOSITORY_NAME` folder first, then mount it as the reports folder of the container using the `-v /builds/$REPOSITORY_HOST/$REPOSITORY_NAME:/opt/robotframework/reports:Z` command-line parameter?

**Comment by ppodgorsek** [comment]
What UID/GID does GitLab rely on to run the image? It is possible to change the container's user using the `--user=1001:1001` parameter, as mentioned in the README: https://github.com/ppodgorsek/docker-robot-framework#security-consideration

**Comment by UnaffiliatedCode** [comment]
i didn't have luck with that previously. I'll give it another whack and update with the result.

**Comment by UnaffiliatedCode** [comment]
So, the user assigned is the Root user. --user=0:0 resolves the issue if i run the image directly. 
However the image is not receiving the files within the parent directory. 

``` yaml
robot testing:
  stage: testing
  image: docker:stable
  artifacts:
    untracked: true
    exclude:
    - "*.tar"
  script:
    - id -u
    - whoami
    - echo $PWD
    - ls -R $PWD/robot/tests
    - docker pull ppodgorsek/robot-framework:latest
    - docker run --user=0:0 -e BROWSER=firefox --volume ${PWD}/robot/tests:/opt/robotframework/tests --volume ${PWD}/robot/reports:/opt/robotframework/reports ppodgorsek/robot-framework:latest 
```
I am still able to replicate the previous error by instead, recompiling this repository on the gitlab remote host and using that image. Once the image is built, and ran, it will complete the tests and respond with no permission to write into the directory from within the container.

With the current version, there are no files within the folder mounted. 
```
$ ls -R $PWD/robot/tests
/********/robot/tests:
common.robot
log.html
output.xml
test1.robot
test2.robot
$ docker pull ppodgorsek/robot-framework:latest
latest: Pulling from ppodgorsek/robot-framework
Digest: sha256:5b159f08e374d6118f01e34509f1cd1fb93ab79db2a8d2f6883b0ea522c1f002
Status: Image is up to date for ppodgorsek/robot-framework:latest
docker.io/ppodgorsek/robot-framework:latest
$ docker run --user=0:0 -e BROWSER=firefox --volume ${PWD}/robot/tests:/opt/robotframework/tests --volume ${PWD}/robot/reports:/opt/robotframework/reports --volume ${PWD}/robot/pageobjects:/opt/robotframework/pageobjects ppodgorsek/robot-framework:latest
[ ERROR ] Suite 'Tests' contains no tests or tasks.
Try --help for usage information.
```

I have an image with the User assignment lines removed, and i can access the image directly, and all works (but takes 30+ minutes to compile and run due to storage limitations)
